### ISSUE TITLE
群晖docker内获取弹幕报错，看起来是获取时区方式与Linux不兼容

### ISSUE THREAD

**Issue by Archer-Tatsu** [cxfksword/jellyfin-plugin-danmu#19]
> [2023-04-16 19:16:25.486 +08:00] [ERR] [33] Jellyfin.Plugin.Danmu.Scrapers.Bilibili.Bilibili: Exception handled GetMatchSeasonId. "流浪地球2"
System.TypeInitializationException: The type initializer for 'Jellyfin.Plugin.Danmu.Core.Utils' threw an exception.
 ---> System.TimeZoneNotFoundException: The time zone ID 'China Standard Time' was not found on the local computer.
 ---> System.IO.FileNotFoundException: Could not find file '/usr/share/zoneinfo/China Standard Time'.
File name: '/usr/share/zoneinfo/China Standard Time'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachineCore(String id, TimeZoneInfo& value, Exception& e)
   --- End of inner exception stack trace ---
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at Jellyfin.Plugin.Danmu.Core.Utils..cctor()
   --- End of inner exception stack trace ---
   at Jellyfin.Plugin.Danmu.Core.Utils.UnixTimeStampToDateTime(Int64 unixTimeStamp)
   at Jellyfin.Plugin.Danmu.Scrapers.Bilibili.Bilibili.Search(BaseItem item)

**Comment by cxfksword** [comment]
最新版改了，你可以试下
