### ISSUE TITLE
接口被风控怎么办

### ISSUE THREAD

**Issue by tossp** [cxfksword/jellyfin-plugin-danmu#2]
```
[12:48:44] [INF] b站没有找到对应视频信息：name=超人总动员
11月 09 12:48:45 jellyfin jellyfin[26419]: [12:48:45] [INF] Processing 1 movies with event type Add
11月 09 12:48:45 jellyfin jellyfin[26419]: [12:48:45] [ERR] Exception handled GetMatchSeasonId. 记忆碎片
11月 09 12:48:45 jellyfin jellyfin[26419]: System.Net.Http.HttpRequestException: Response status code does not indicate success: 412 (Precondition Failed).
11月 09 12:48:45 jellyfin jellyfin[26419]:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
11月 09 12:48:45 jellyfin jellyfin[26419]:    at Jellyfin.Plugin.Danmu.Api.BilibiliApi.SearchAsync(String keyword, CancellationToken cancellationToken)
11月 09 12:48:45 jellyfin jellyfin[26419]:    at Jellyfin.Plugin.Danmu.Providers.LibraryManagerEventsHelper.GetMatchSeasonId(BaseItem item, String searchName)
``

**Comment by cxfksword** [comment]
你等1/2小时后，再试下，我后面限制下搜索接口的请求频率
