### ISSUE TITLE
部分番剧的b站弹幕下载出现了问题，这是其中的日志。其他错误都是这个报错形式

### ISSUE THREAD

**Issue by Kongsama171** [cxfksword/jellyfin-plugin-danmu#30]
```
[2024-01-15 20:25:35.874 +08:00] [ERR] [8] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: ["bilibili"]Exception handled download danmu file. name="剑"
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
   at System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.<CopyToAsync>g__Core|11_0(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jellyfin.Plugin.Danmu.Scrapers.Bilibili.BilibiliApi.GetDanmuContentByCidAsync(Int64 cid, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Danmu.Scrapers.Bilibili.Bilibili.GetDanmuContent(BaseItem item, String commentId)
   at Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper.DownloadDanmu(AbstractScraper scraper, BaseItem item, String commentId, Boolean ignoreCheck)
```

**Comment by cxfksword** [comment]
哪部番剧？看日志是100秒超时了，可以试下重新下载或检查网络有没问题

**Comment by Kongsama171** [comment]
不太像是网络问题。因为日志里面全是这种一个下载成功和100秒超时的error连在一起，然后连着好几十对
![image](https://github.com/cxfksword/jellyfin-plugin-danmu/assets/86615415/1c63d6a7-5c9b-48b6-8f7a-b026ef8f81e7)
