### ISSUE TITLE
弹幕不能下载了，之前下载了的弹幕又可以继续更新，求教

### ISSUE THREAD

**Issue by asingletear** [cxfksword/jellyfin-plugin-danmu#36]
修改字幕，可以搜索到弹幕，但是点下载没反应，附上日志。。。
测试后发现，之前下载好的弹幕，从任务里是可以更新弹幕的，但是搜索下载一样不行。。。

Jellyfin.Plugin.Danmu.Core.CanIgnoreException: 弹幕下载已由Danmu插件接管.
[18:01:45] [INF] [152] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: Movie force: 猪猪侠大电影·星际行动
[18:01:45] [ERR] [152] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: Error in OnQueueTimerCallbackInternal
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.BaseItem> MediaBrowser.Controller.Entities.TV.Season.GetEpisodes(Jellyfin.Data.Entities.User, MediaBrowser.Controller.Dto.DtoOptions)'.
   at Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper.ProcessQueuedSeasonEvents(IReadOnlyCollection`1 events, EventType eventType)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper.ProcessQueuedSeasonEvents(IReadOnlyCollection`1 events, EventType eventType)
   at Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper.OnQueueTimerCallbackInternal()
   at Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper.OnQueueTimerCallback(Object state)

**Comment by asingletear** [comment]
插件卸载重装了，还是不行~~~

**Comment by cxfksword** [comment]
新版修正了

**Comment by asingletear** [comment]
我的jellyfin和弹幕插件都是最新版啊，莫名其妙出现的问题
