### ISSUE TITLE
弹幕保存路径问题

### ISSUE THREAD

**Issue by wx2020** [cxfksword/jellyfin-plugin-danmu#60]
请问所有弹幕是保存到本地的吗？我在触发扫描任务后发现日志有报错：
```
[2024-10-25 12:52:56.617 +00:00] [INF] [96] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: 更新epid到元数据完成。item数：20
[2024-10-25 12:52:56.617 +00:00] [INF] [96] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: ["bilibili"]匹配失败："爱情公寓" (2014)
[2024-10-25 12:52:56.617 +00:00] [INF] [96] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: ["弹弹play"]匹配失败："爱情公寓" (2014)
[2024-10-25 12:52:56.617 +00:00] [INF] [96] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: ["优酷"]匹配失败："爱情公寓" (2014)
[2024-10-25 12:52:58.426 +00:00] [INF] [157] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: ["爱奇艺"]匹配成功：name="爱情公寓" season_number=4 ProviderId: "19rrgzy5ls"
[2024-10-25 12:52:58.433 +00:00] [INF] [157] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: 更新epid到元数据完成。item数：1
[2024-10-25 12:52:58.436 +00:00] [INF] [157] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: ["爱奇艺"]成功匹配. 1."真相只有一个" -> epId: "19rrgzy5ls" cid: "221865100"
[2024-10-25 12:53:00.822 +00:00] [ERR] [96] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: ["爱奇艺"]Exception handled download danmu file. name="真相只有一个"
System.IO.IOException: Read-only file system : '/data/tv_series/Ipartment.2014.S04.Complete.1080p.WEB-DL.H264.AAC-TJUPT/Ipartment.2014.S04E01.1080p.WEB-DL.H264.AAC-TJUPT.xml'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.<WriteAllBytesAsync>g__Core|92_0(String path, Byte[] bytes, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper.SaveDanmu(BaseItem item, Byte[] bytes)
   at Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper.DownloadDanmu(AbstractScraper scraper, BaseItem item, String commentId, Boolean ignoreCheck)
```
因为我挂载docker磁盘的方式是只读，所以会报错，对插件的行为有疑问，所以咨询一下

**Comment by cxfksword** [comment]
是保存本地
