### ISSUE TITLE
电视剧匹配到优酷源，返回连接错误，下载不了

### ISSUE THREAD

**Issue by OliverTwistOl** [cxfksword/jellyfin-plugin-danmu#65]
[2024-11-12 10:39:10.685 +08:00] [ERR] [40] Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper: ["优酷"]Exception handled download danmu file. name="燕子京杀人被官府带走"
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jellyfin.Plugin.Danmu.Scrapers.Youku.YoukuApi.EnsureTokenCookie(CancellationToken cancellationToken)
   at Jellyfin.Plugin.Danmu.Scrapers.Youku.YoukuApi.GetDanmuContentAsync(String vid, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Danmu.Scrapers.Youku.Youku.GetDanmuContent(BaseItem item, String commentId)
   at Jellyfin.Plugin.Danmu.LibraryManagerEventsHelper.DownloadDanmu(AbstractScraper scraper, BaseItem item, String commentId, Boolean ignoreCheck)

**Comment by OliverTwistOl** [comment]
关闭梯子就好了。。。
